#!/usr/bin/env python3
# Copyright (c) 2026 Durable State contributors | MIT License
"""
Generate a checksums.sha256 manifest for a directory you are about to SHIP.

Why this is a tool and not a committed file: a manifest inside a git repository
rots on every commit - the moment you edit a file it lies, and once it has lied
once nobody trusts it again. Git is the integrity mechanism for a repository.
A manifest is for the moment of distribution: a zip, a release asset, a backup.

    python tools/make_manifest.py .                  # manifest in the CWD
    python tools/make_manifest.py dist/ -o dist/checksums.sha256
    python tools/make_manifest.py dist/ --verify     # check and exit 1 on damage
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from durable_state.verify import sha256_of, verify_dir  # noqa: E402

SKIP_DIRS = {"__pycache__", ".git", ".pytest_cache", ".crash", ".venv", "build", "dist", ".tox"}


def collect(root: Path) -> list[Path]:
    out = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if p.name == "checksums.sha256" or p.suffix == ".pyc":
            continue
        out.append(p)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("-o", "--output", default=None)
    ap.add_argument("--verify", action="store_true", help="verify instead of writing")
    args = ap.parse_args()

    root = Path(args.root).resolve()

    if args.verify:
        report = verify_dir(root)
        print("checked: %d | ok: %s" % (report["checked"], report["ok"]))
        for key in ("hash_mismatch", "missing", "not_utf8", "has_bom"):
            if report[key]:
                print("  %s: %s" % (key, report[key]))
        return 0 if report["ok"] else 1

    files = collect(root)
    out = Path(args.output) if args.output else root / "checksums.sha256"
    lines = [
        "# sha256 manifest - generated by tools/make_manifest.py",
        "# verify with: python -m durable_state.verify %s" % root.name,
        "#",
    ]
    lines += ["%s  %s" % (sha256_of(p), p.relative_to(root).as_posix()) for p in files]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%d files)" % (out, len(files)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
